package com.zoho.crm.api.record

import com.zoho.crm.api.layouts.Layouts
import com.zoho.crm.api.record.Comment
import com.zoho.crm.api.record.Consent
import com.zoho.crm.api.record.Participants
import com.zoho.crm.api.record.PricingDetails
import com.zoho.crm.api.record.Record
import com.zoho.crm.api.record.RecurringActivity
import com.zoho.crm.api.record.RemindAt
import com.zoho.crm.api.record.Reminder
import com.zoho.crm.api.record.Tax
import com.zoho.crm.api.record.Territory
import com.zoho.crm.api.record.TimeRange
import com.zoho.crm.api.users.MinifiedUser
import com.zoho.crm.api.util.Choice
import java.time.LocalDate
import java.time.OffsetDateTime
import scala.collection.mutable.ArrayBuffer

class Field[T](var apiName: String)	{

	def getAPIName() :String	={
		return  this.apiName
	}}
 object Field{
class Products		{
		final val ProductCategory:Field[Choice[String]] = new Field[Choice[String]]("Product_Category")
		final val QtyInDemand:Field[Double] = new Field[Double]("Qty_in_Demand")
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Description:Field[String] = new Field[String]("Description")
		final val VendorName:Field[Record] = new Field[Record]("Vendor_Name")
		final val SalesStartDate:Field[LocalDate] = new Field[LocalDate]("Sales_Start_Date")
		final val Tax:Field[ArrayBuffer[Tax]] = new Field[ArrayBuffer[Tax]]("Tax")
		final val ProductActive:Field[Boolean] = new Field[Boolean]("Product_Active")
		final val RecordImage:Field[String] = new Field[String]("Record_Image")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val ProductCode:Field[String] = new Field[String]("Product_Code")
		final val Manufacturer:Field[Choice[String]] = new Field[Choice[String]]("Manufacturer")
		final val id:Field[Long] = new Field[Long]("id")
		final val SupportExpiryDate:Field[LocalDate] = new Field[LocalDate]("Support_Expiry_Date")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val CommissionRate:Field[Double] = new Field[Double]("Commission_Rate")
		final val ProductName:Field[String] = new Field[String]("Product_Name")
		final val Handler:Field[MinifiedUser] = new Field[MinifiedUser]("Handler")
		final val SupportStartDate:Field[LocalDate] = new Field[LocalDate]("Support_Start_Date")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val UsageUnit:Field[Choice[String]] = new Field[Choice[String]]("Usage_Unit")
		final val QtyOrdered:Field[Double] = new Field[Double]("Qty_Ordered")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val QtyInStock:Field[Double] = new Field[Double]("Qty_in_Stock")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val SalesEndDate:Field[LocalDate] = new Field[LocalDate]("Sales_End_Date")
		final val UnitPrice:Field[Double] = new Field[Double]("Unit_Price")
		final val ReorderLevel:Field[Double] = new Field[Double]("Reorder_Level")
		final val Taxable:Field[Boolean] = new Field[Boolean]("Taxable")
	}


class Consents		{
		final val ContactThroughEmail:Field[Boolean] = new Field[Boolean]("Contact_Through_Email")
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val Email:Field[String] = new Field[String]("Email")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val ConsentThrough:Field[Choice[String]] = new Field[Choice[String]]("Consent_Through")
		final val ContactThroughSurvey:Field[Boolean] = new Field[Boolean]("Contact_Through_Survey")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val DataProcessingBasis:Field[Choice[String]] = new Field[Choice[String]]("Data_Processing_Basis")
		final val ContactThroughPhone:Field[Boolean] = new Field[Boolean]("Contact_Through_Phone")
		final val LawfulReason:Field[String] = new Field[String]("Lawful_Reason")
		final val MailSentTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Mail_Sent_Time")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val ConsentDate:Field[LocalDate] = new Field[LocalDate]("Consent_Date")
		final val id:Field[Long] = new Field[Long]("id")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val ConsentRemarks:Field[String] = new Field[String]("Consent_Remarks")
	}


class Tasks		{
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val Description:Field[String] = new Field[String]("Description")
		final val DueDate:Field[LocalDate] = new Field[LocalDate]("Due_Date")
		final val Priority:Field[Choice[String]] = new Field[Choice[String]]("Priority")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val ClosedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Closed_Time")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val Subject:Field[String] = new Field[String]("Subject")
		final val SendNotificationEmail:Field[Boolean] = new Field[Boolean]("Send_Notification_Email")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val RecurringActivity:Field[RecurringActivity] = new Field[RecurringActivity]("Recurring_Activity")
		final val WhatId:Field[Record] = new Field[Record]("What_Id")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val id:Field[Long] = new Field[Long]("id")
		final val RemindAt:Field[RemindAt] = new Field[RemindAt]("Remind_At")
		final val WhoId:Field[Record] = new Field[Record]("Who_Id")
	}


class Data_Subject_Requests		{
		final val RequestType:Field[Choice[String]] = new Field[Choice[String]]("Request_Type")
		final val IsClosed:Field[String] = new Field[String]("Is_Closed")
		final val ParentId:Field[Record] = new Field[Record]("Parent_Id")
		final val RequestSource:Field[Choice[String]] = new Field[Choice[String]]("Request_Source")
		final val id:Field[Long] = new Field[Long]("id")
		final val ClosedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Closed_By")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val RequestedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Requested_By")
		final val RequestedDate:Field[OffsetDateTime] = new Field[OffsetDateTime]("Requested_Date")
		final val ClosedDate:Field[OffsetDateTime] = new Field[OffsetDateTime]("Closed_Date")
	}


class Vendors		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Email:Field[String] = new Field[String]("Email")
		final val Category:Field[String] = new Field[String]("Category")
		final val Description:Field[String] = new Field[String]("Description")
		final val VendorName:Field[String] = new Field[String]("Vendor_Name")
		final val Website:Field[String] = new Field[String]("Website")
		final val RecordImage:Field[String] = new Field[String]("Record_Image")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val UnsubscribedMode:Field[Choice[String]] = new Field[Choice[String]]("Unsubscribed_Mode")
		final val Phone:Field[String] = new Field[String]("Phone")
		final val Street:Field[String] = new Field[String]("Street")
		final val ZipCode:Field[String] = new Field[String]("Zip_Code")
		final val id:Field[Long] = new Field[Long]("id")
		final val EmailOptOut:Field[Boolean] = new Field[Boolean]("Email_Opt_Out")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val UnsubscribedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Unsubscribed_Time")
		final val City:Field[String] = new Field[String]("City")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val State:Field[String] = new Field[String]("State")
		final val GLAccount:Field[Choice[String]] = new Field[Choice[String]]("GL_Account")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val Country:Field[String] = new Field[String]("Country")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
	}


class Appointments__s		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Address:Field[String] = new Field[String]("Address")
		final val AppointmentStartTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Appointment_Start_Time")
		final val CancellationReason:Field[Choice[String]] = new Field[Choice[String]]("Cancellation_Reason")
		final val AppointmentFor:Field[Record] = new Field[Record]("Appointment_For")
		final val RescheduledTo:Field[OffsetDateTime] = new Field[OffsetDateTime]("Rescheduled_To")
		final val RescheduleReason:Field[Choice[String]] = new Field[Choice[String]]("Reschedule_Reason")
		final val JobSheetNameS:Field[String] = new Field[String]("Job_Sheet_Name__s")
		final val AdditionalInformation:Field[String] = new Field[String]("Additional_Information")
		final val JobSheetCreatedS:Field[Boolean] = new Field[Boolean]("Job_Sheet_Created__s")
		final val CancelledTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Cancelled_Time")
		final val CancellationNote:Field[String] = new Field[String]("Cancellation_Note")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val RescheduleCount:Field[Int] = new Field[Int]("Reschedule_Count")
		final val RescheduledBy:Field[MinifiedUser] = new Field[MinifiedUser]("Rescheduled_By")
		final val id:Field[Long] = new Field[Long]("id")
		final val RescheduledTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Rescheduled_Time")
		final val RemindAt:Field[ArrayBuffer[Reminder]] = new Field[ArrayBuffer[Reminder]]("Remind_At")
		final val AppointmentEndTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Appointment_End_Time")
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val ServiceName:Field[Record] = new Field[Record]("Service_Name")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val RescheduledFrom:Field[OffsetDateTime] = new Field[OffsetDateTime]("Rescheduled_From")
		final val CancelledBy:Field[MinifiedUser] = new Field[MinifiedUser]("Cancelled_By")
		final val AppointmentName:Field[String] = new Field[String]("Appointment_Name")
		final val Duration:Field[Int] = new Field[Int]("Duration")
		final val JobSheetSectionS:Field[Choice[String]] = new Field[Choice[String]]("Job_Sheet_Section__s")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val JobSheetDescriptionS:Field[String] = new Field[String]("Job_Sheet_Description__s")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val Location:Field[Choice[String]] = new Field[Choice[String]]("Location")
		final val RescheduleNote:Field[String] = new Field[String]("Reschedule_Note")
	}


class Calls		{
		final val CallDuration:Field[String] = new Field[String]("Call_Duration")
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Description:Field[String] = new Field[String]("Description")
		final val CTIEntry:Field[Boolean] = new Field[Boolean]("CTI_Entry")
		final val CallerID:Field[String] = new Field[String]("Caller_ID")
		final val CallAgenda:Field[String] = new Field[String]("Call_Agenda")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val CallPurpose:Field[Choice[String]] = new Field[Choice[String]]("Call_Purpose")
		final val id:Field[Long] = new Field[Long]("id")
		final val WhoId:Field[Record] = new Field[Record]("Who_Id")
		final val OutgoingCallStatus:Field[Choice[String]] = new Field[Choice[String]]("Outgoing_Call_Status")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val Reminder:Field[Choice[String]] = new Field[Choice[String]]("Reminder")
		final val VoiceRecordingS:Field[String] = new Field[String]("Voice_Recording__s")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val CallStartTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Call_Start_Time")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val Subject:Field[String] = new Field[String]("Subject")
		final val CallType:Field[Choice[String]] = new Field[Choice[String]]("Call_Type")
		final val CallResult:Field[String] = new Field[String]("Call_Result")
		final val ScheduledInCRM:Field[Choice[String]] = new Field[Choice[String]]("Scheduled_In_CRM")
		final val WhatId:Field[Record] = new Field[Record]("What_Id")
		final val CallDurationInSeconds:Field[Int] = new Field[Int]("Call_Duration_in_seconds")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val DialledNumber:Field[String] = new Field[String]("Dialled_Number")
	}


class Leads		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Company:Field[String] = new Field[String]("Company")
		final val Email:Field[String] = new Field[String]("Email")
		final val VisitorScore:Field[Long] = new Field[Long]("Visitor_Score")
		final val LastActivityTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Activity_Time")
		final val Industry:Field[Choice[String]] = new Field[Choice[String]]("Industry")
		final val UnsubscribedMode:Field[Choice[String]] = new Field[Choice[String]]("Unsubscribed_Mode")
		final val ExchangeRate:Field[Double] = new Field[Double]("Exchange_Rate")
		final val Currency:Field[Choice[String]] = new Field[Choice[String]]("Currency")
		final val Street:Field[String] = new Field[String]("Street")
		final val ZipCode:Field[String] = new Field[String]("Zip_Code")
		final val DataProcessingBasisDetails:Field[Consent] = new Field[Consent]("Data_Processing_Basis_Details")
		final val id:Field[Long] = new Field[Long]("id")
		final val DataSource:Field[Choice[String]] = new Field[Choice[String]]("Data_Source")
		final val EnrichStatusS:Field[Choice[String]] = new Field[Choice[String]]("Enrich_Status__s")
		final val FirstVisitedURL:Field[String] = new Field[String]("First_Visited_URL")
		final val DaysVisited:Field[Int] = new Field[Int]("Days_Visited")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val ChangeLogTimeS:Field[OffsetDateTime] = new Field[OffsetDateTime]("Change_Log_Time__s")
		final val City:Field[String] = new Field[String]("City")
		final val NoOfEmployees:Field[Int] = new Field[Int]("No_of_Employees")
		final val DataProcessingBasis:Field[Choice[String]] = new Field[Choice[String]]("Data_Processing_Basis")
		final val ConvertedS:Field[Boolean] = new Field[Boolean]("Converted__s")
		final val ConvertedDateTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Converted_Date_Time")
		final val ConvertedAccount:Field[Record] = new Field[Record]("Converted_Account")
		final val State:Field[String] = new Field[String]("State")
		final val Country:Field[String] = new Field[String]("Country")
		final val LastVisitedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Visited_Time")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val AnnualRevenue:Field[Double] = new Field[Double]("Annual_Revenue")
		final val SecondaryEmail:Field[String] = new Field[String]("Secondary_Email")
		final val Description:Field[String] = new Field[String]("Description")
		final val NumberOfChats:Field[Int] = new Field[Int]("Number_Of_Chats")
		final val Rating:Field[Choice[String]] = new Field[Choice[String]]("Rating")
		final val Website:Field[String] = new Field[String]("Website")
		final val Twitter:Field[String] = new Field[String]("Twitter")
		final val AverageTimeSpentMinutes:Field[Double] = new Field[Double]("Average_Time_Spent_Minutes")
		final val Salutation:Field[Choice[String]] = new Field[Choice[String]]("Salutation")
		final val FirstName:Field[String] = new Field[String]("First_Name")
		final val LeadStatus:Field[Choice[String]] = new Field[Choice[String]]("Lead_Status")
		final val FullName:Field[String] = new Field[String]("Full_Name")
		final val RecordImage:Field[String] = new Field[String]("Record_Image")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val ConvertedDeal:Field[Record] = new Field[Record]("Converted_Deal")
		final val LeadConversionTime:Field[Int] = new Field[Int]("Lead_Conversion_Time")
		final val SkypeID:Field[String] = new Field[String]("Skype_ID")
		final val Phone:Field[String] = new Field[String]("Phone")
		final val EmailOptOut:Field[Boolean] = new Field[Boolean]("Email_Opt_Out")
		final val Designation:Field[String] = new Field[String]("Designation")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val UnsubscribedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Unsubscribed_Time")
		final val ConvertedContact:Field[Record] = new Field[Record]("Converted_Contact")
		final val Mobile:Field[String] = new Field[String]("Mobile")
		final val Territories:Field[ArrayBuffer[Territory]] = new Field[ArrayBuffer[Territory]]("Territories")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val FirstVisitedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("First_Visited_Time")
		final val LastName:Field[String] = new Field[String]("Last_Name")
		final val Layout:Field[Layouts] = new Field[Layouts]("Layout")
		final val Referrer:Field[String] = new Field[String]("Referrer")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val LeadSource:Field[Choice[String]] = new Field[Choice[String]]("Lead_Source")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val Fax:Field[String] = new Field[String]("Fax")
		final val LastEnrichedTimeS:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Enriched_Time__s")
	}


class Deals		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Description:Field[String] = new Field[String]("Description")
		final val CampaignSource:Field[Record] = new Field[Record]("Campaign_Source")
		final val ClosingDate:Field[LocalDate] = new Field[LocalDate]("Closing_Date")
		final val LastActivityTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Activity_Time")
		final val ReasonForLossS:Field[Choice[String]] = new Field[Choice[String]]("Reason_For_Loss__s")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val LeadConversionTime:Field[Int] = new Field[Int]("Lead_Conversion_Time")
		final val DealName:Field[String] = new Field[String]("Deal_Name")
		final val ExchangeRate:Field[Double] = new Field[Double]("Exchange_Rate")
		final val ExpectedRevenue:Field[Double] = new Field[Double]("Expected_Revenue")
		final val Currency:Field[Choice[String]] = new Field[Choice[String]]("Currency")
		final val OverallSalesDuration:Field[Int] = new Field[Int]("Overall_Sales_Duration")
		final val Stage:Field[Choice[String]] = new Field[Choice[String]]("Stage")
		final val AccountName:Field[Record] = new Field[Record]("Account_Name")
		final val id:Field[Long] = new Field[Long]("id")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val Territory:Field[ArrayBuffer[Territory]] = new Field[ArrayBuffer[Territory]]("Territory")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val Amount:Field[Double] = new Field[Double]("Amount")
		final val Probability:Field[Int] = new Field[Int]("Probability")
		final val NextStep:Field[String] = new Field[String]("Next_Step")
		final val ChangeLogTimeS:Field[OffsetDateTime] = new Field[OffsetDateTime]("Change_Log_Time__s")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val ContactName:Field[Record] = new Field[Record]("Contact_Name")
		final val Pipeline:Field[Choice[String]] = new Field[Choice[String]]("Pipeline")
		final val SalesCycleDuration:Field[Int] = new Field[Int]("Sales_Cycle_Duration")
		final val Type:Field[Choice[String]] = new Field[Choice[String]]("Type")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val LeadSource:Field[Choice[String]] = new Field[Choice[String]]("Lead_Source")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
	}


class Quotes		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Description:Field[String] = new Field[String]("Description")
		final val Discount:Field[Double] = new Field[Double]("Discount")
		final val ShippingState:Field[String] = new Field[String]("Shipping_State")
		final val Tax:Field[Double] = new Field[Double]("Tax")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val DealName:Field[Record] = new Field[Record]("Deal_Name")
		final val ExchangeRate:Field[Double] = new Field[Double]("Exchange_Rate")
		final val ValidTill:Field[LocalDate] = new Field[LocalDate]("Valid_Till")
		final val BillingCountry:Field[String] = new Field[String]("Billing_Country")
		final val Currency:Field[Choice[String]] = new Field[Choice[String]]("Currency")
		final val Team:Field[String] = new Field[String]("Team")
		final val AccountName:Field[Record] = new Field[Record]("Account_Name")
		final val Carrier:Field[Choice[String]] = new Field[Choice[String]]("Carrier")
		final val QuotedItems:Field[ArrayBuffer[Record]] = new Field[ArrayBuffer[Record]]("Quoted_Items")
		final val id:Field[Long] = new Field[Long]("id")
		final val QuoteStage:Field[Choice[String]] = new Field[Choice[String]]("Quote_Stage")
		final val GrandTotal:Field[Double] = new Field[Double]("Grand_Total")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val Adjustment:Field[Double] = new Field[Double]("Adjustment")
		final val BillingStreet:Field[String] = new Field[String]("Billing_Street")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val TermsAndConditions:Field[String] = new Field[String]("Terms_and_Conditions")
		final val SubTotal:Field[Double] = new Field[Double]("Sub_Total")
		final val BillingCode:Field[String] = new Field[String]("Billing_Code")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val Subject:Field[String] = new Field[String]("Subject")
		final val ContactName:Field[Record] = new Field[Record]("Contact_Name")
		final val ShippingCity:Field[String] = new Field[String]("Shipping_City")
		final val ShippingCountry:Field[String] = new Field[String]("Shipping_Country")
		final val ShippingCode:Field[String] = new Field[String]("Shipping_Code")
		final val BillingCity:Field[String] = new Field[String]("Billing_City")
		final val QuoteNumber:Field[String] = new Field[String]("Quote_Number")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val BillingState:Field[String] = new Field[String]("Billing_State")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val ShippingStreet:Field[String] = new Field[String]("Shipping_Street")
	}


class Invoices		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Description:Field[String] = new Field[String]("Description")
		final val Discount:Field[Double] = new Field[Double]("Discount")
		final val ShippingState:Field[String] = new Field[String]("Shipping_State")
		final val Tax:Field[Double] = new Field[Double]("Tax")
		final val InvoiceDate:Field[LocalDate] = new Field[LocalDate]("Invoice_Date")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val InvoicedItems:Field[ArrayBuffer[Record]] = new Field[ArrayBuffer[Record]]("Invoiced_Items")
		final val ExchangeRate:Field[Double] = new Field[Double]("Exchange_Rate")
		final val BillingCountry:Field[String] = new Field[String]("Billing_Country")
		final val Currency:Field[Choice[String]] = new Field[Choice[String]]("Currency")
		final val AccountName:Field[Record] = new Field[Record]("Account_Name")
		final val id:Field[Long] = new Field[Long]("id")
		final val SalesOrder:Field[Record] = new Field[Record]("Sales_Order")
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val SalesCommission:Field[Double] = new Field[Double]("Sales_Commission")
		final val GrandTotal:Field[Double] = new Field[Double]("Grand_Total")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val DueDate:Field[LocalDate] = new Field[LocalDate]("Due_Date")
		final val Adjustment:Field[Double] = new Field[Double]("Adjustment")
		final val BillingStreet:Field[String] = new Field[String]("Billing_Street")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val TermsAndConditions:Field[String] = new Field[String]("Terms_and_Conditions")
		final val SubTotal:Field[Double] = new Field[Double]("Sub_Total")
		final val InvoiceNumber:Field[String] = new Field[String]("Invoice_Number")
		final val BillingCode:Field[String] = new Field[String]("Billing_Code")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val Subject:Field[String] = new Field[String]("Subject")
		final val ExciseDuty:Field[Double] = new Field[Double]("Excise_Duty")
		final val ContactName:Field[Record] = new Field[Record]("Contact_Name")
		final val ShippingCity:Field[String] = new Field[String]("Shipping_City")
		final val ShippingCountry:Field[String] = new Field[String]("Shipping_Country")
		final val ShippingCode:Field[String] = new Field[String]("Shipping_Code")
		final val BillingCity:Field[String] = new Field[String]("Billing_City")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val PurchaseOrder:Field[String] = new Field[String]("Purchase_Order")
		final val BillingState:Field[String] = new Field[String]("Billing_State")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val ShippingStreet:Field[String] = new Field[String]("Shipping_Street")
	}


class Campaigns		{
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val Description:Field[String] = new Field[String]("Description")
		final val CampaignName:Field[String] = new Field[String]("Campaign_Name")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val EndDate:Field[LocalDate] = new Field[LocalDate]("End_Date")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val Type:Field[Choice[String]] = new Field[Choice[String]]("Type")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val NumSent:Field[Long] = new Field[Long]("Num_sent")
		final val ExchangeRate:Field[Double] = new Field[Double]("Exchange_Rate")
		final val ExpectedRevenue:Field[Double] = new Field[Double]("Expected_Revenue")
		final val Currency:Field[Choice[String]] = new Field[Choice[String]]("Currency")
		final val ActualCost:Field[Double] = new Field[Double]("Actual_Cost")
		final val ExpectedResponse:Field[Long] = new Field[Long]("Expected_Response")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val ParentCampaign:Field[Record] = new Field[Record]("Parent_Campaign")
		final val id:Field[Long] = new Field[Long]("id")
		final val StartDate:Field[LocalDate] = new Field[LocalDate]("Start_Date")
		final val BudgetedCost:Field[Double] = new Field[Double]("Budgeted_Cost")
	}


class Attachments		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val FileName:Field[String] = new Field[String]("File_Name")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val Size:Field[Long] = new Field[Long]("Size")
		final val ParentId:Field[Record] = new Field[Record]("Parent_Id")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val id:Field[Long] = new Field[Long]("id")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
	}


class Price_Books		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val PricingDetails:Field[ArrayBuffer[PricingDetails]] = new Field[ArrayBuffer[PricingDetails]]("Pricing_Details")
		final val Description:Field[String] = new Field[String]("Description")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val Active:Field[Boolean] = new Field[Boolean]("Active")
		final val PricingModel:Field[Choice[String]] = new Field[Choice[String]]("Pricing_Model")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val PriceBookName:Field[String] = new Field[String]("Price_Book_Name")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val id:Field[Long] = new Field[Long]("id")
	}


class Sales_Orders		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Description:Field[String] = new Field[String]("Description")
		final val Discount:Field[Double] = new Field[Double]("Discount")
		final val CustomerNo:Field[String] = new Field[String]("Customer_No")
		final val ShippingState:Field[String] = new Field[String]("Shipping_State")
		final val Tax:Field[Double] = new Field[Double]("Tax")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val DealName:Field[Record] = new Field[Record]("Deal_Name")
		final val ExchangeRate:Field[Double] = new Field[Double]("Exchange_Rate")
		final val BillingCountry:Field[String] = new Field[String]("Billing_Country")
		final val Currency:Field[Choice[String]] = new Field[Choice[String]]("Currency")
		final val AccountName:Field[Record] = new Field[Record]("Account_Name")
		final val Carrier:Field[Choice[String]] = new Field[Choice[String]]("Carrier")
		final val id:Field[Long] = new Field[Long]("id")
		final val OrderedItems:Field[ArrayBuffer[Record]] = new Field[ArrayBuffer[Record]]("Ordered_Items")
		final val QuoteName:Field[Record] = new Field[Record]("Quote_Name")
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val SalesCommission:Field[Double] = new Field[Double]("Sales_Commission")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val DueDate:Field[LocalDate] = new Field[LocalDate]("Due_Date")
		final val Adjustment:Field[Double] = new Field[Double]("Adjustment")
		final val BillingStreet:Field[String] = new Field[String]("Billing_Street")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val TermsAndConditions:Field[String] = new Field[String]("Terms_and_Conditions")
		final val SubTotal:Field[Double] = new Field[Double]("Sub_Total")
		final val BillingCode:Field[String] = new Field[String]("Billing_Code")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val Subject:Field[String] = new Field[String]("Subject")
		final val ContactName:Field[Record] = new Field[Record]("Contact_Name")
		final val ExciseDuty:Field[Double] = new Field[Double]("Excise_Duty")
		final val ShippingCity:Field[String] = new Field[String]("Shipping_City")
		final val ShippingCountry:Field[String] = new Field[String]("Shipping_Country")
		final val ShippingCode:Field[String] = new Field[String]("Shipping_Code")
		final val BillingCity:Field[String] = new Field[String]("Billing_City")
		final val SONumber:Field[String] = new Field[String]("SO_Number")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val PurchaseOrder:Field[String] = new Field[String]("Purchase_Order")
		final val BillingState:Field[String] = new Field[String]("Billing_State")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val Pending:Field[String] = new Field[String]("Pending")
		final val ShippingStreet:Field[String] = new Field[String]("Shipping_Street")
	}


class Services__s		{
		final val JobSheetRequired:Field[Choice[String]] = new Field[Choice[String]]("Job_Sheet_Required")
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Description:Field[String] = new Field[String]("Description")
		final val AvailableDays:Field[ArrayBuffer[Choice[String]]] = new Field[ArrayBuffer[Choice[String]]]("Available_Days")
		final val Tax:Field[ArrayBuffer[Choice[String]]] = new Field[ArrayBuffer[Choice[String]]]("Tax")
		final val UnavailableFrom:Field[OffsetDateTime] = new Field[OffsetDateTime]("Unavailable_From")
		final val RecordImage:Field[String] = new Field[String]("Record_Image")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val id:Field[Long] = new Field[Long]("id")
		final val AvailableDates:Field[LocalDate] = new Field[LocalDate]("Available_Dates")
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val AvailableTimings:Field[ArrayBuffer[TimeRange]] = new Field[ArrayBuffer[TimeRange]]("Available_Timings")
		final val ServiceName:Field[String] = new Field[String]("Service_Name")
		final val AvailableFrom:Field[LocalDate] = new Field[LocalDate]("Available_From")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val AvailableTill:Field[LocalDate] = new Field[LocalDate]("Available_Till")
		final val Duration:Field[Int] = new Field[Int]("Duration")
		final val JobSheetSectionS:Field[Choice[String]] = new Field[Choice[String]]("Job_Sheet_Section__s")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val Price:Field[Double] = new Field[Double]("Price")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val AvailabilityType:Field[Choice[String]] = new Field[Choice[String]]("Availability_Type")
		final val Members:Field[ArrayBuffer[Record]] = new Field[ArrayBuffer[Record]]("Members")
		final val Location:Field[Choice[String]] = new Field[Choice[String]]("Location")
		final val UnavailableTill:Field[OffsetDateTime] = new Field[OffsetDateTime]("Unavailable_Till")
	}


class Contacts		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Email:Field[String] = new Field[String]("Email")
		final val VisitorScore:Field[Long] = new Field[Long]("Visitor_Score")
		final val OtherPhone:Field[String] = new Field[String]("Other_Phone")
		final val MailingState:Field[String] = new Field[String]("Mailing_State")
		final val OtherState:Field[String] = new Field[String]("Other_State")
		final val OtherCountry:Field[String] = new Field[String]("Other_Country")
		final val LastActivityTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Activity_Time")
		final val Department:Field[String] = new Field[String]("Department")
		final val UnsubscribedMode:Field[Choice[String]] = new Field[Choice[String]]("Unsubscribed_Mode")
		final val Assistant:Field[String] = new Field[String]("Assistant")
		final val MailingCountry:Field[String] = new Field[String]("Mailing_Country")
		final val DataProcessingBasisDetails:Field[Consent] = new Field[Consent]("Data_Processing_Basis_Details")
		final val id:Field[Long] = new Field[Long]("id")
		final val DataSource:Field[Choice[String]] = new Field[Choice[String]]("Data_Source")
		final val ReportingTo:Field[Record] = new Field[Record]("Reporting_To")
		final val EnrichStatusS:Field[Choice[String]] = new Field[Choice[String]]("Enrich_Status__s")
		final val FirstVisitedURL:Field[String] = new Field[String]("First_Visited_URL")
		final val DaysVisited:Field[Int] = new Field[Int]("Days_Visited")
		final val OtherCity:Field[String] = new Field[String]("Other_City")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val ChangeLogTimeS:Field[OffsetDateTime] = new Field[OffsetDateTime]("Change_Log_Time__s")
		final val DataProcessingBasis:Field[Choice[String]] = new Field[Choice[String]]("Data_Processing_Basis")
		final val HomePhone:Field[String] = new Field[String]("Home_Phone")
		final val LastVisitedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Visited_Time")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val SecondaryEmail:Field[String] = new Field[String]("Secondary_Email")
		final val Description:Field[String] = new Field[String]("Description")
		final val VendorName:Field[Record] = new Field[Record]("Vendor_Name")
		final val MailingZip:Field[String] = new Field[String]("Mailing_Zip")
		final val ReportsTo:Field[String] = new Field[String]("Reports_To")
		final val NumberOfChats:Field[Int] = new Field[Int]("Number_Of_Chats")
		final val OtherZip:Field[String] = new Field[String]("Other_Zip")
		final val Twitter:Field[String] = new Field[String]("Twitter")
		final val MailingStreet:Field[String] = new Field[String]("Mailing_Street")
		final val AverageTimeSpentMinutes:Field[Double] = new Field[Double]("Average_Time_Spent_Minutes")
		final val Salutation:Field[Choice[String]] = new Field[Choice[String]]("Salutation")
		final val FirstName:Field[String] = new Field[String]("First_Name")
		final val AsstPhone:Field[String] = new Field[String]("Asst_Phone")
		final val FullName:Field[String] = new Field[String]("Full_Name")
		final val RecordImage:Field[String] = new Field[String]("Record_Image")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val SkypeID:Field[String] = new Field[String]("Skype_ID")
		final val Phone:Field[String] = new Field[String]("Phone")
		final val AccountName:Field[Record] = new Field[Record]("Account_Name")
		final val EmailOptOut:Field[Boolean] = new Field[Boolean]("Email_Opt_Out")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val DateOfBirth:Field[LocalDate] = new Field[LocalDate]("Date_of_Birth")
		final val MailingCity:Field[String] = new Field[String]("Mailing_City")
		final val UnsubscribedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Unsubscribed_Time")
		final val Title:Field[String] = new Field[String]("Title")
		final val OtherStreet:Field[String] = new Field[String]("Other_Street")
		final val Mobile:Field[String] = new Field[String]("Mobile")
		final val Territories:Field[ArrayBuffer[Territory]] = new Field[ArrayBuffer[Territory]]("Territories")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val FirstVisitedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("First_Visited_Time")
		final val LastName:Field[String] = new Field[String]("Last_Name")
		final val Referrer:Field[String] = new Field[String]("Referrer")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val LeadSource:Field[Choice[String]] = new Field[Choice[String]]("Lead_Source")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val Fax:Field[String] = new Field[String]("Fax")
		final val LastEnrichedTimeS:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Enriched_Time__s")
	}


class Solutions		{
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val Comments:Field[ArrayBuffer[Comment]] = new Field[ArrayBuffer[Comment]]("Comments")
		final val NoOfComments:Field[Int] = new Field[Int]("No_of_comments")
		final val ProductName:Field[Record] = new Field[Record]("Product_Name")
		final val AddComment:Field[String] = new Field[String]("Add_Comment")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val SolutionNumber:Field[String] = new Field[String]("Solution_Number")
		final val Answer:Field[String] = new Field[String]("Answer")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val SolutionTitle:Field[String] = new Field[String]("Solution_Title")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val Published:Field[Boolean] = new Field[Boolean]("Published")
		final val Question:Field[String] = new Field[String]("Question")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val id:Field[Long] = new Field[Long]("id")
	}


class Events		{
		final val AllDay:Field[Boolean] = new Field[Boolean]("All_day")
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val CheckInState:Field[String] = new Field[String]("Check_In_State")
		final val CheckInAddress:Field[String] = new Field[String]("Check_In_Address")
		final val Description:Field[String] = new Field[String]("Description")
		final val RemindParticipants:Field[ArrayBuffer[Reminder]] = new Field[ArrayBuffer[Reminder]]("Remind_Participants")
		final val StartDateTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Start_DateTime")
		final val Latitude:Field[Double] = new Field[Double]("Latitude")
		final val Participants:Field[ArrayBuffer[Participants]] = new Field[ArrayBuffer[Participants]]("Participants")
		final val EventTitle:Field[String] = new Field[String]("Event_Title")
		final val CheckInBy:Field[MinifiedUser] = new Field[MinifiedUser]("Check_In_By")
		final val EndDateTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("End_DateTime")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val CheckInCity:Field[String] = new Field[String]("Check_In_City")
		final val id:Field[Long] = new Field[Long]("id")
		final val CheckInComment:Field[String] = new Field[String]("Check_In_Comment")
		final val RemindAt:Field[ArrayBuffer[Reminder]] = new Field[ArrayBuffer[Reminder]]("Remind_At")
		final val WhoId:Field[Record] = new Field[Record]("Who_Id")
		final val CheckInStatus:Field[String] = new Field[String]("Check_In_Status")
		final val CheckInCountry:Field[String] = new Field[String]("Check_In_Country")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val Venue:Field[String] = new Field[String]("Venue")
		final val ZIPCode:Field[String] = new Field[String]("ZIP_Code")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val Longitude:Field[Double] = new Field[Double]("Longitude")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val CheckInTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Check_In_Time")
		final val RecurringActivity:Field[RecurringActivity] = new Field[RecurringActivity]("Recurring_Activity")
		final val WhatId:Field[Record] = new Field[Record]("What_Id")
		final val CheckInSubLocality:Field[String] = new Field[String]("Check_In_Sub_Locality")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
	}


class Purchase_Orders		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Description:Field[String] = new Field[String]("Description")
		final val Discount:Field[Double] = new Field[Double]("Discount")
		final val VendorName:Field[Record] = new Field[Record]("Vendor_Name")
		final val ShippingState:Field[String] = new Field[String]("Shipping_State")
		final val Tax:Field[Double] = new Field[Double]("Tax")
		final val PODate:Field[LocalDate] = new Field[LocalDate]("PO_Date")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val ExchangeRate:Field[Double] = new Field[Double]("Exchange_Rate")
		final val BillingCountry:Field[String] = new Field[String]("Billing_Country")
		final val Currency:Field[Choice[String]] = new Field[Choice[String]]("Currency")
		final val PurchaseItems:Field[ArrayBuffer[Record]] = new Field[ArrayBuffer[Record]]("Purchase_Items")
		final val Carrier:Field[Choice[String]] = new Field[Choice[String]]("Carrier")
		final val id:Field[Long] = new Field[Long]("id")
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val SalesCommission:Field[Double] = new Field[Double]("Sales_Commission")
		final val GrandTotal:Field[Double] = new Field[Double]("Grand_Total")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val PONumber:Field[String] = new Field[String]("PO_Number")
		final val DueDate:Field[LocalDate] = new Field[LocalDate]("Due_Date")
		final val Adjustment:Field[Double] = new Field[Double]("Adjustment")
		final val BillingStreet:Field[String] = new Field[String]("Billing_Street")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val TermsAndConditions:Field[String] = new Field[String]("Terms_and_Conditions")
		final val SubTotal:Field[Double] = new Field[Double]("Sub_Total")
		final val BillingCode:Field[String] = new Field[String]("Billing_Code")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val Subject:Field[String] = new Field[String]("Subject")
		final val TrackingNumber:Field[String] = new Field[String]("Tracking_Number")
		final val ContactName:Field[Record] = new Field[Record]("Contact_Name")
		final val ExciseDuty:Field[Double] = new Field[Double]("Excise_Duty")
		final val ShippingCity:Field[String] = new Field[String]("Shipping_City")
		final val ShippingCountry:Field[String] = new Field[String]("Shipping_Country")
		final val ShippingCode:Field[String] = new Field[String]("Shipping_Code")
		final val BillingCity:Field[String] = new Field[String]("Billing_City")
		final val RequisitionNo:Field[String] = new Field[String]("Requisition_No")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val BillingState:Field[String] = new Field[String]("Billing_State")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val ShippingStreet:Field[String] = new Field[String]("Shipping_Street")
	}


class Accounts		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Ownership:Field[Choice[String]] = new Field[Choice[String]]("Ownership")
		final val Description:Field[String] = new Field[String]("Description")
		final val AccountType:Field[Choice[String]] = new Field[Choice[String]]("Account_Type")
		final val Rating:Field[Choice[String]] = new Field[Choice[String]]("Rating")
		final val SICCode:Field[Int] = new Field[Int]("SIC_Code")
		final val ShippingState:Field[String] = new Field[String]("Shipping_State")
		final val Website:Field[String] = new Field[String]("Website")
		final val Employees:Field[Int] = new Field[Int]("Employees")
		final val LastActivityTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Activity_Time")
		final val Industry:Field[Choice[String]] = new Field[Choice[String]]("Industry")
		final val RecordImage:Field[String] = new Field[String]("Record_Image")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val AccountSite:Field[String] = new Field[String]("Account_Site")
		final val ExchangeRate:Field[Double] = new Field[Double]("Exchange_Rate")
		final val Phone:Field[String] = new Field[String]("Phone")
		final val BillingCountry:Field[String] = new Field[String]("Billing_Country")
		final val Currency:Field[Choice[String]] = new Field[Choice[String]]("Currency")
		final val AccountName:Field[String] = new Field[String]("Account_Name")
		final val id:Field[Long] = new Field[Long]("id")
		final val AccountNumber:Field[Long] = new Field[Long]("Account_Number")
		final val TickerSymbol:Field[String] = new Field[String]("Ticker_Symbol")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val BillingStreet:Field[String] = new Field[String]("Billing_Street")
		final val EnrichStatusS:Field[Choice[String]] = new Field[Choice[String]]("Enrich_Status__s")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val ChangeLogTimeS:Field[OffsetDateTime] = new Field[OffsetDateTime]("Change_Log_Time__s")
		final val BillingCode:Field[String] = new Field[String]("Billing_Code")
		final val Territories:Field[ArrayBuffer[Territory]] = new Field[ArrayBuffer[Territory]]("Territories")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val ParentAccount:Field[Record] = new Field[Record]("Parent_Account")
		final val ShippingCity:Field[String] = new Field[String]("Shipping_City")
		final val ShippingCountry:Field[String] = new Field[String]("Shipping_Country")
		final val ShippingCode:Field[String] = new Field[String]("Shipping_Code")
		final val BillingCity:Field[String] = new Field[String]("Billing_City")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val BillingState:Field[String] = new Field[String]("Billing_State")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val Fax:Field[String] = new Field[String]("Fax")
		final val AnnualRevenue:Field[Double] = new Field[Double]("Annual_Revenue")
		final val LastEnrichedTimeS:Field[OffsetDateTime] = new Field[OffsetDateTime]("Last_Enriched_Time__s")
		final val ShippingStreet:Field[String] = new Field[String]("Shipping_Street")
	}


class Cases		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val Email:Field[String] = new Field[String]("Email")
		final val Description:Field[String] = new Field[String]("Description")
		final val InternalComments:Field[String] = new Field[String]("Internal_Comments")
		final val NoOfComments:Field[Int] = new Field[Int]("No_of_comments")
		final val ReportedBy:Field[String] = new Field[String]("Reported_By")
		final val CaseNumber:Field[String] = new Field[String]("Case_Number")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val DealName:Field[Record] = new Field[Record]("Deal_Name")
		final val Phone:Field[String] = new Field[String]("Phone")
		final val AccountName:Field[Record] = new Field[Record]("Account_Name")
		final val id:Field[Long] = new Field[Long]("id")
		final val Solution:Field[String] = new Field[String]("Solution")
		final val Status:Field[Choice[String]] = new Field[Choice[String]]("Status")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val Priority:Field[Choice[String]] = new Field[Choice[String]]("Priority")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val Comments:Field[ArrayBuffer[Comment]] = new Field[ArrayBuffer[Comment]]("Comments")
		final val ProductName:Field[Record] = new Field[Record]("Product_Name")
		final val AddComment:Field[String] = new Field[String]("Add_Comment")
		final val CaseOrigin:Field[Choice[String]] = new Field[Choice[String]]("Case_Origin")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
		final val CaseReason:Field[Choice[String]] = new Field[Choice[String]]("Case_Reason")
		final val Subject:Field[String] = new Field[String]("Subject")
		final val Type:Field[Choice[String]] = new Field[Choice[String]]("Type")
		final val LockedS:Field[Boolean] = new Field[Boolean]("Locked__s")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val Tag:Field[String] = new Field[String]("Tag")
		final val RelatedTo:Field[Record] = new Field[Record]("Related_To")
	}


class Notes		{
		final val Owner:Field[MinifiedUser] = new Field[MinifiedUser]("Owner")
		final val ModifiedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Modified_By")
		final val ModifiedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Modified_Time")
		final val CreatedTime:Field[OffsetDateTime] = new Field[OffsetDateTime]("Created_Time")
		final val ParentId:Field[Record] = new Field[Record]("Parent_Id")
		final val AssociatedIdS:Field[Long] = new Field[Long]("Associated_Id__s")
		final val CreatedBy:Field[MinifiedUser] = new Field[MinifiedUser]("Created_By")
		final val id:Field[Long] = new Field[Long]("id")
		final val NoteTitle:Field[String] = new Field[String]("Note_Title")
		final val NoteContent:Field[String] = new Field[String]("Note_Content")
		final val RecordStatusS:Field[Choice[String]] = new Field[Choice[String]]("Record_Status__s")
	}
}
